#!/usr/bin/env python3
import os
import ssl
import sys

import nltk

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

if "https_proxy" in os.environ:
    nltk.set_proxy(os.environ["https_proxy"])

sys.stderr.write("This will take some time\n")

nltk.download("all")
